paths_file = 'config/paths.yaml'
general_conf_file = 'config/general.yaml'
test_transforms_conf_file = 'config/test_transforms.yaml'

path_train = 'config/exp1_train'
path_trainstarted = 'config/exp1_train_started'
path_pred = 'config/exp2_pred'
path_predstarted = 'config/exp2_pred_started'
path_measure = 'config/exp3_measure'
path_measurestarted = 'config/exp3_measure_started'
